'use client'

import Link from 'next/link'
import { useEffect, useState } from 'react'
import { ArrowRight, BarChart3, CheckCircle2, Leaf, ShieldCheck, Users } from 'lucide-react'
import type { LucideIcon } from 'lucide-react'

type OverviewData = {
  marketsMonitored: number
  verifiedBuyerSignals: number
  averageLotReadiness: number
  updatedAt: string
}

export default function Landing() {
  const [overview, setOverview] = useState<OverviewData | null>(null)

  useEffect(() => {
    fetch('/api/overview', { cache: 'no-store' })
      .then(async (response) => {
        if (!response.ok) throw new Error('Unable to load overview data.')
        const payload = await response.json() as { data: OverviewData }
        setOverview(payload.data)
      })
      .catch(() => setOverview(null))
  }, [])

  return <main className="clyden-page-bg min-h-screen text-foreground">
    <header className="mx-auto flex max-w-7xl items-center justify-between gap-4 px-5 py-5 sm:px-8"><Link href="/" className="flex shrink-0 items-center gap-2 text-lg font-semibold"><span className="flex size-9 items-center justify-center rounded-xl bg-primary text-primary-foreground"><Leaf className="size-5" /></span>CLYDEN</Link><nav className="hidden items-center gap-6 text-sm text-muted-foreground lg:flex"><a href="#about">About CLYDEN</a><a href="#how-it-works">How it works</a><a href="#benefits">Benefits</a><a href="#insights">Market insights</a><a href="#opportunities">Opportunities</a></nav><div className="flex items-center gap-2"><a href="#register" className="hidden text-sm font-medium text-muted-foreground sm:inline">Register</a><Link href="/login" className="rounded-lg bg-primary px-4 py-2.5 text-sm font-semibold text-primary-foreground">Login</Link></div></header>
    <section className="clyden-shine relative mx-3 overflow-hidden rounded-2xl border border-border bg-card shadow-sm sm:mx-6 lg:mx-auto lg:max-w-7xl"><div className="clyden-grid pointer-events-none absolute inset-0 opacity-70" aria-hidden="true" /><div className="pointer-events-none absolute -right-16 -top-16 size-48 rounded-full border border-accent/25 bg-accent/10 blur-sm clyden-float" aria-hidden="true" /><div className="relative grid lg:grid-cols-[1.05fr_0.95fr]"><div className="flex flex-col justify-center p-7 sm:p-12 lg:p-16"><div className="mb-5 inline-flex w-fit items-center gap-2 rounded-full border border-primary/15 bg-primary/5 px-3 py-1.5 text-xs font-semibold text-primary"><span className="size-1.5 rounded-full bg-primary" />Agricultural trade intelligence</div><h1 className="max-w-2xl text-balance text-4xl font-semibold tracking-[-0.04em] sm:text-6xl">Every decision after harvest, in one place.</h1><p className="mt-5 max-w-xl text-pretty text-base leading-7 text-muted-foreground sm:text-lg">CLYDEN helps sellers, buyers, and operators turn market signals into confident action.</p><div className="mt-8 flex flex-col gap-3 sm:flex-row"><Link href="/seller" className="inline-flex items-center justify-center gap-2 rounded-lg bg-primary px-5 py-3 text-sm font-semibold text-primary-foreground">Open seller workspace <ArrowRight className="size-4" /></Link><Link href="/buyer" className="inline-flex items-center justify-center gap-2 rounded-lg border border-border px-5 py-3 text-sm font-semibold">Browse as buyer</Link></div></div><div className="relative min-h-56 overflow-hidden bg-secondary sm:min-h-72 lg:min-h-full"><img src="/agrobridge-hero.png" alt="Nigerian farmer beside green crop rows" className="size-full object-cover object-center" /><div className="absolute inset-0 bg-gradient-to-r from-secondary/35 to-transparent" /><div className="absolute bottom-5 left-5 rounded-xl border border-white/30 bg-foreground/80 px-4 py-3 text-primary-foreground backdrop-blur-sm"><p className="text-xs font-medium text-primary-foreground/70">Live network signal</p><p className="mt-1 text-sm font-semibold">18 markets monitored today</p></div></div></div></section>
    <section id="about" className="mx-auto max-w-7xl px-5 pb-16 pt-12 sm:px-8 lg:pb-24 lg:pt-20"><div className="grid gap-8 lg:grid-cols-[0.8fr_1.2fr] lg:items-center"><div><p className="text-xs font-semibold uppercase tracking-[0.16em] text-primary">About CLYDEN</p><h2 className="mt-3 max-w-lg text-3xl font-semibold tracking-tight sm:text-4xl">The clearer way to move agricultural value.</h2><p className="mt-5 max-w-2xl text-pretty leading-7 text-muted-foreground">CLYDEN brings market signals, verified supply, buyer demand, and trade coordination into one connected workspace, so every participant can make better decisions with less friction.</p></div><div className="clyden-shine relative min-h-56 overflow-hidden rounded-2xl border border-border bg-secondary"><img src="/clyden-market.png" alt="Agricultural market trader reviewing supply information" className="absolute inset-0 size-full object-cover" /><div className="absolute inset-0 bg-gradient-to-r from-foreground/75 via-foreground/20 to-transparent" /><div className="relative flex h-full min-h-56 items-end p-5 text-primary-foreground"><div className="rounded-xl border border-white/20 bg-foreground/50 px-4 py-3 backdrop-blur-sm"><p className="text-xs text-primary-foreground/70">One connected market view</p><p className="mt-1 text-sm font-semibold">From field signal to opportunity.</p></div></div></div></div></section>
    <section id="roles" className="relative mx-auto max-w-7xl overflow-hidden px-5 py-16 sm:px-8 lg:py-24"><div className="pointer-events-none absolute -right-20 top-8 size-64 rounded-full border border-primary/10 bg-primary/[0.025]" aria-hidden="true" /><div className="pointer-events-none absolute right-16 top-24 size-20 rounded-full border border-accent/30" aria-hidden="true" /><div className="relative max-w-xl"><p className="text-xs font-semibold uppercase tracking-[0.16em] text-primary">One network, clearer decisions</p><h2 className="mt-3 text-3xl font-semibold tracking-tight sm:text-4xl">The operating layer between harvest and market.</h2></div><div className="mt-10 grid gap-4 md:grid-cols-3"><RoleCard icon={BarChart3} title="Seller intelligence" text="Know when to sell, which route pays best, and what your next shipment needs." href="/seller" /><RoleCard icon={Users} title="Buyer procurement" text="Discover verified supply, compare quality, and move from shortlist to purchase." href="/buyer" /><RoleCard icon={ShieldCheck} title="Admin control" text="Monitor marketplace health, verification, logistics, and platform activity." href="/admin" /></div></section>
    <section id="benefits" className="mx-auto max-w-7xl px-5 py-16 sm:px-8 lg:py-24"><div className="max-w-xl"><p className="text-xs font-semibold uppercase tracking-[0.16em] text-primary">Benefits</p><h2 className="mt-3 text-3xl font-semibold tracking-tight sm:text-4xl">Less guesswork. More movement.</h2></div><div className="mt-10 grid gap-4 md:grid-cols-3"><RoleCard icon={BarChart3} title="See the market" text="Turn price, demand, and route signals into a confident next move." href="#insights" /><RoleCard icon={ShieldCheck} title="Trade with trust" text="Keep verification, readiness, and quality signals close to every opportunity." href="#opportunities" /><RoleCard icon={Users} title="Work together" text="Give sellers, buyers, and operators a shared source of truth." href="#register" /></div></section>
    <section id="how-it-works" className="border-y border-border bg-secondary/40"><div className="mx-auto grid max-w-7xl gap-8 px-5 py-16 sm:px-8 lg:grid-cols-2 lg:gap-x-12 lg:gap-y-4 lg:py-24"><div className="relative min-h-56 overflow-hidden rounded-2xl border border-primary/10 bg-primary p-6 text-primary-foreground"><div className="clyden-grid absolute inset-0 opacity-20" aria-hidden="true" /><div className="relative flex h-full min-h-52 flex-col justify-between"><div className="flex items-center justify-between"><span className="flex size-10 items-center justify-center rounded-xl bg-primary-foreground/10"><BarChart3 className="size-5" /></span><span className="rounded-full bg-accent px-3 py-1 text-xs font-semibold text-accent-foreground">Live signal</span></div><div><p className="text-3xl font-semibold">03</p><p className="mt-1 text-sm text-primary-foreground/70">steps to a clearer trade</p></div><div className="flex gap-2"><span className="h-1.5 flex-1 rounded-full bg-accent" /><span className="h-1.5 flex-1 rounded-full bg-primary-foreground/20" /><span className="h-1.5 flex-1 rounded-full bg-primary-foreground/20" /></div></div></div><div className="lg:col-start-2 lg:row-start-1"><p className="text-xs font-semibold uppercase tracking-[0.16em] text-primary">How it works</p><h2 className="mt-3 text-3xl font-semibold tracking-tight sm:text-4xl">From field signal to fulfilled order.</h2></div><div className="flex flex-col gap-7">{[['01','Read the market','See demand, prices, route costs, and timing in one view.'],['02','Make the match','Connect the right lot with a verified buyer and clear terms.'],['03','Move with proof','Track handoffs, documents, and delivery through the trust layer.']].map(([number,title,text]) => <div key={number} className="flex gap-4"><span className="font-mono text-sm text-primary">{number}</span><div><h3 className="font-semibold">{title}</h3><p className="mt-1 text-sm leading-6 text-muted-foreground">{text}</p></div></div>)}</div></div></section>
    <section id="insights" className="relative mx-auto max-w-7xl overflow-hidden px-5 py-16 sm:px-8 lg:py-24"><div className="pointer-events-none absolute -left-12 top-20 size-32 rounded-full bg-accent/20 blur-3xl clyden-float-delay" aria-hidden="true" /><div className="relative rounded-2xl border border-border bg-card p-6 shadow-sm sm:p-10"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="text-xs font-semibold uppercase tracking-[0.16em] text-primary">Market insights</p><h2 className="mt-3 text-3xl font-semibold tracking-tight sm:text-4xl">Signals you can act on.</h2></div><span className="text-sm text-muted-foreground">{overview?.updatedAt ? `Updated ${new Date(overview.updatedAt).toLocaleDateString('en-NG', { day: 'numeric', month: 'short' })}` : 'Loading signals'}</span></div><div className="mt-8 grid gap-4 md:grid-cols-3"><Metric value={overview ? String(overview.marketsMonitored) : '—'} label="markets monitored" /><Metric value={overview ? String(overview.verifiedBuyerSignals) : '—'} label="verified buyer signals" /><Metric value={overview ? `${overview.averageLotReadiness}%` : '—'} label="average lot readiness" /></div></div></section>
    <section id="opportunities" className="mx-auto max-w-7xl px-5 pb-16 sm:px-8 lg:pb-24"><div className="mb-8 flex flex-col justify-between gap-3 sm:flex-row sm:items-end"><div><p className="text-xs font-semibold uppercase tracking-[0.16em] text-primary">Featured opportunities</p><h2 className="mt-3 text-3xl font-semibold tracking-tight sm:text-4xl">Where the network is moving.</h2></div><Link href="/buyer" className="text-sm font-semibold text-primary">View buyer workspace <ArrowRight className="ml-1 inline size-4" /></Link></div><div className="grid gap-4 md:grid-cols-3"><div className="group overflow-hidden rounded-2xl border border-border bg-card shadow-sm transition duration-300 hover:-translate-y-1 hover:shadow-lg"><div className="relative h-32 overflow-hidden bg-secondary"><img src="/clyden-opportunity.png" alt="Agricultural samples prepared for trade" className="size-full object-cover transition duration-500 group-hover:scale-105" /><div className="absolute inset-0 bg-gradient-to-t from-foreground/60 to-transparent" /></div><div className="p-5"><p className="text-xs text-muted-foreground">Sesame · Kano</p><h3 className="mt-3 font-semibold">Export-ready lots</h3><p className="mt-2 text-sm leading-6 text-muted-foreground">Verified supply with strong international demand signals.</p></div></div><div className="group rounded-2xl border border-border bg-card p-5 shadow-sm transition duration-300 hover:-translate-y-1 hover:shadow-lg"><div className="mb-5 flex size-11 items-center justify-center rounded-xl bg-accent/25 text-accent-foreground transition group-hover:rotate-3"><ArrowRight className="size-5" /></div><p className="text-xs text-muted-foreground">Ginger · Kaduna</p><h3 className="mt-3 font-semibold">Early buyer interest</h3><p className="mt-2 text-sm leading-6 text-muted-foreground">Secure a conversation before the next price shift.</p></div><div className="group rounded-2xl border border-border bg-card p-5 shadow-sm transition duration-300 hover:-translate-y-1 hover:shadow-lg"><div className="mb-5 flex size-11 items-center justify-center rounded-xl bg-primary/10 text-primary transition group-hover:scale-105"><ShieldCheck className="size-5" /></div><p className="text-xs text-muted-foreground">Maize · Plateau</p><h3 className="mt-3 font-semibold">Regional demand gap</h3><p className="mt-2 text-sm leading-6 text-muted-foreground">Connect available stock with nearby verified buyers.</p></div></div></section>
    <section id="trust" className="mx-auto max-w-7xl px-5 py-16 sm:px-8 lg:py-24"><div className="grid gap-4 lg:grid-cols-[0.85fr_1.15fr]"><div className="relative min-h-64 overflow-hidden rounded-2xl border border-border bg-secondary"><img src="/agrobridge-supply.png" alt="Agricultural produce sacks in a warehouse" className="absolute inset-0 size-full object-cover" /><div className="absolute inset-0 bg-gradient-to-t from-foreground/75 via-foreground/10 to-transparent" /><div className="absolute bottom-5 left-5 text-primary-foreground"><p className="text-xs text-primary-foreground/70">The trust layer</p><p className="mt-1 text-lg font-semibold">Proof travels with the lot.</p></div></div><div className="rounded-2xl border border-border bg-card p-6 sm:p-10"><div className="grid gap-8 md:grid-cols-3"><Metric value="18" label="markets monitored" /><Metric value="42" label="verified buyer signals" /><Metric value="86%" label="average lot readiness" /></div><div className="mt-10 flex flex-col gap-4 border-t border-border pt-6 sm:flex-row sm:items-center sm:justify-between"><div className="flex items-center gap-3"><CheckCircle2 className="size-5 text-primary" /><p className="text-sm text-muted-foreground">Built around traceability, clear economics, and human decisions.</p></div><Link href="/seller" className="text-sm font-semibold text-primary">Explore the workspace <ArrowRight className="ml-1 inline size-4" /></Link></div></div>    </div></section>
    <section id="register" className="mx-3 mb-12 overflow-hidden rounded-2xl bg-primary px-6 py-10 text-primary-foreground sm:mx-6 sm:px-10 lg:mx-auto lg:max-w-7xl lg:py-14"><div className="flex flex-col justify-between gap-7 lg:flex-row lg:items-center"><div><p className="text-xs font-semibold uppercase tracking-[0.16em] text-accent">Join CLYDEN</p><h2 className="mt-3 max-w-xl text-3xl font-semibold tracking-tight sm:text-4xl">Bring your next trade into focus.</h2></div><div className="flex flex-col gap-3 sm:flex-row"><Link href="/seller" className="inline-flex items-center justify-center rounded-lg bg-accent px-5 py-3 text-sm font-semibold text-accent-foreground">Seller registration</Link><Link href="/buyer" className="inline-flex items-center justify-center rounded-lg border border-primary-foreground/30 px-5 py-3 text-sm font-semibold text-primary-foreground">Buyer registration</Link></div></div></section>
    <footer className="mx-auto flex max-w-7xl flex-col gap-2 px-5 pb-8 text-xs text-muted-foreground sm:flex-row sm:justify-between sm:px-8"><span>CLYDEN</span><span>Agricultural market intelligence · Demo environment</span></footer>
  </main>
}
function RoleCard({ icon: Icon, title, text, href }: { icon: LucideIcon; title: string; text: string; href: string }) { return <Link href={href} className="group relative overflow-hidden rounded-2xl border border-border bg-card p-6 shadow-sm transition duration-300 hover:-translate-y-1 hover:border-primary/40 hover:shadow-lg hover:shadow-primary/10"><div className="flex size-10 items-center justify-center rounded-xl bg-primary/10 text-primary"><Icon className="size-5" /></div><h3 className="mt-5 font-semibold">{title}</h3><p className="mt-2 text-sm leading-6 text-muted-foreground">{text}</p><span className="mt-5 inline-flex items-center gap-2 text-sm font-semibold text-primary">Explore <ArrowRight className="size-4 transition group-hover:translate-x-1" /></span></Link> }
function Metric({ value, label }: { value: string; label: string }) { return <div><p className="text-3xl font-semibold text-primary">{value}</p><p className="mt-1 text-sm text-muted-foreground">{label}</p></div> }
function SimpleHeader({ role }: { role: string }) { return <header className="sticky top-0 z-30 flex min-h-16 items-center justify-between border-b border-border bg-card/95 px-4 backdrop-blur sm:px-8"><Link href="/" className="flex items-center gap-2 font-semibold text-foreground"><span className="flex size-8 items-center justify-center rounded-lg bg-primary text-primary-foreground"><Leaf className="size-4" /></span>CLYDEN</Link><nav className="hidden items-center gap-1 rounded-lg bg-secondary p-1 md:flex"><Link href="/seller" className={`rounded-md px-3 py-1.5 text-xs font-medium ${role === 'Seller' ? 'bg-card text-primary shadow-sm' : 'text-muted-foreground'}`}>Seller</Link><Link href="/buyer" className={`rounded-md px-3 py-1.5 text-xs font-medium ${role === 'Buyer' ? 'bg-card text-primary shadow-sm' : 'text-muted-foreground'}`}>Buyer</Link><Link href="/admin" className={`rounded-md px-3 py-1.5 text-xs font-medium ${role === 'Admin' ? 'bg-card text-primary shadow-sm' : 'text-muted-foreground'}`}>Admin</Link></nav><div className="flex items-center gap-3"><span className="hidden text-xs text-muted-foreground sm:inline">{role} workspace</span><Link href="/api/auth/logout" className="text-sm font-medium text-primary">Log out</Link></div></header> }
export { SimpleHeader }
